info:
  addr: :10100
  name: idgenerator
  id: 100
log:
  path: 
  console: true
  level: INFO
DB:
  path:
cache:
  path:
  mmapsize: 0x80000
  datasize: 0x2000
  prealloc: 100
dump:
  invertal: 5
  addr: 